### ISSUE TITLE
Caching requests

### ISSUE THREAD

**Issue by scls19fr** [eadwinCode/shoutcast_api#2]
Hello @eadwinCode,

I noticed you are using [python-requests](https://requests.readthedocs.io/).
I think you can quite easily implement a way to cache queries using [requests-cache](https://github.com/reclosedev/requests-cache)

See how it's being used in https://pandas-datareader.readthedocs.io/en/latest/cache.html passing `session=None` by default or passing `session=requests_cache.CachedSession(...)`

See also
https://github.com/pydata/pandas-datareader/blob/adb67b2e959f2060a9db18f8b343d06e917f23da/pandas_datareader/_utils.py#L56-L60

Kind regards

**Comment by eadwinCode** [comment]
@scls19fr thanks for your suggestions. I will look into it.
