### ISSUE TITLE
Rename environment variable

### ISSUE THREAD

**Issue by scls19fr** [eadwinCode/shoutcast_api#3]
Hello,

I noticed

https://github.com/eadwinCode/shoutcast_api/blob/2f7904b8178e39a46d93397b50efc3a42a03cd76/tests/test_genres.py#L8
(and in other test files)

Maybe you should name this environment variable differently to avoid confusion between several API keys.

Generally, environment variables are upper cased.

`SHOUTCAST_API_KEY` could be a better name for that purpose.

Kind regards

**Comment by eadwinCode** [comment]
Alright.
